#pragma once

#define SEETA_FACE_DETECTOR_MAJOR_VERSION 2
#define SEETA_FACE_DETECTOR_MINOR_VERSION 5
#define SEETA_FACE_DETECTOR_SINOR_VERSION 5

#define SEETA_FACE_DETECTOR_LIBRARY_NAME "SeetaFaceDetector"

#define SEETA_FACE_DETECTOR_NAMESPACE_VERSION v2
