#pragma once

#define SEETA_FACE_RECOGNIZER_MAJOR_VERSION 2
#define SEETA_FACE_RECOGNIZER_MINOR_VERSION 5
#define SEETA_FACE_RECOGNIZER_SINOR_VERSION 5

#define SEETA_FACE_RECOGNIZER_LIBRARY_NAME "SeetaFaceRecognizer"

#define SEETA_FACE_RECOGNIZER_NAMESPACE_VERSION v2
